### PR TITLE
ES-1750 Update sonar-ps-plugin to LTA 2026.1 compatibility

### PR DESCRIPTION
**Pull request by hbcartojano**
This updates the `sonar-ps-plugin` so it's compatible with SonarQube Server LTA 2026.1. 

**Dependency Updates**
- **sonar-plugin-api**: `10.11.0.2468` → `13.4.3.4290` (compatible with LTA 2026.1)
- **sonar-testing-harness**: `10.7.0.96327` → `26.1.0.118079` (compatible with LTA 2026.1)
- **commons-lang3**: `3.12.0` → `3.18.0` (minimum to resolve issue)

Left comments below on file changes outside https://github.com/gretard/sonar-ps-plugin/pull/39
All tests pass and plugin works as intended in SonarQube Community 26.1.0.118079

### CODE REVIEW

File: sonar-ps-plugin/.settings/org.eclipse.jdt.core.prefs [hunk 1]
```diff
@@ -1,8 +1,12 @@
...
+org.eclipse.jdt.core.compiler.codegen.targetPlatform=21
+org.eclipse.jdt.core.compiler.compliance=21
 org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
+org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled
 org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
 org.eclipse.jdt.core.compiler.problem.forbiddenReference=warning
-org.eclipse.jdt.core.compiler.source=1.8
+org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures=ignore
+org.eclipse.jdt.core.compiler.processAnnotations=disabled
+org.eclipse.jdt.core.compiler.release=enabled
```
Comment (hbcartojano) [inline sonar-ps-plugin/.settings/org.eclipse.jdt.core.prefs:11]: - `forbiddenReference=warning` - Allows Eclipse to compile code using `provided` scope dependencies (like sonar-plugin-api) without errors
- `release=enabled` - Matches Maven's `<release>21</release>` compiler setting to ensure Java 21 compatibility
- `processAnnotations=disabled` - Skips annotation processing (not used in this project)
- `reportPreviewFeatures=ignore` - Suppresses warnings for Java preview features

File: sonar-ps-plugin/.settings/org.eclipse.jdt.core.prefs [hunk 2]
```diff
@@ -1,8 +1,12 @@
 eclipse.preferences.version=1
 org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
-org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
-org.eclipse.jdt.core.compiler.compliance=1.8
+org.eclipse.jdt.core.compiler.codegen.targetPlatform=21
+org.eclipse.jdt.core.compiler.compliance=21
```
Comment (hbcartojano) [inline sonar-ps-plugin/.settings/org.eclipse.jdt.core.prefs:4]: SonarQuber Server LTA 2026 has dropped support of Java 17.

File: sonar-ps-plugin/.classpath [hunk 3]
```diff
@@ -9,20 +9,24 @@
...
 	</classpathentry>
 	<classpathentry excluding="**" kind="src" output="target/test-classes" path="src/test/resources">
 		<attributes>
 			<attribute name="maven.pomderived" value="true"/>
+			<attribute name="test" value="true"/>
+			<attribute name="optional" value="true"/>
 		</attributes>
 	</classpathentry>
-	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER">
+	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-21">
```
Comment (hbcartojano) [inline sonar-ps-plugin/.classpath:29]: Sonarqube Server LTA 2026 has dropped support of Java 17.

File: sonar-ps-plugin/pom.xml [hunk 4]
```diff
@@ -41,23 +42,16 @@
...
-			<artifactId>sonar-plugin-api-impl</artifactId>
-			<version>${sonar.apiVersion}</version>
-			<scope>test</scope>
-		</dependency>
-
 		<dependency>
 			<groupId>org.apache.commons</groupId>
 			<artifactId>commons-lang3</artifactId>
-			<version>3.12.0</version>
+			<version>3.18.0</version>
```
Comment (hbcartojano) [inline sonar-ps-plugin/pom.xml:54]: When upgrading the testing harness to 26.1, tests failed with:
```
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Strings
```

Root Cause: The newer `sonar-plugin-api-impl` (26.4) internally uses `org.apache.commons.lang3.Strings` class, which was introduced in commons-lang3 3.18.0. The project's explicit dependency on 3.12.0 was causing Maven to resolve the older version, preventing the `Strings` class from being available at test runtime.

Solution: Upgraded `commons-lang3` to 3.18.0 to align with the transitive dependency requirements of sonar-plugin-api-impl 26.4

File: sonar-ps-plugin/pom.xml [hunk 5]
```diff
@@ -99,10 +100,9 @@
 			<plugin>
 				<groupId>org.apache.maven.plugins</groupId>
 				<artifactId>maven-compiler-plugin</artifactId>
-				<version>3.5.1</version>
+				<version>3.13.0</version>
```
Comment (hbcartojano) [inline sonar-ps-plugin/pom.xml:103]: Version 3.5.1 (2016) is 8 years old and doesn't fully support Java 21 features.

File: sonar-ps-plugin/src/main/java/org/sonar/plugins/powershell/PowershellLanguage.java [hunk 6]
```diff
@@ -9,21 +9,16 @@ public class PowershellLanguage extends AbstractLanguage {
...
+        this.config = config;
     }
 
     public String[] getFileSuffixes() {
-        final String[] suffixes = this.settings.getStringArray(Constants.FILE_SUFFIXES);
-        if (suffixes == null || suffixes.length == 0) {
-            return DEFAULT_FILE_SUFFIXES;
-        }
-        return suffixes;
+        return this.config.get("sonar.ps.file.suffixes").map(s -> s.split(",")).orElse(DEFAULT_FILE_SUFFIXES);
```
Comment (hbcartojano) [inline sonar-ps-plugin/src/main/java/org/sonar/plugins/powershell/PowershellLanguage.java:21]: Code style improvement from https://github.com/iress/sonar-ps-plugin/pull/2/changes/331dabfd6ce16e3adbd1abfee5f68193b286f94b#diff-9c7d812c183193df8a2d26d8743452cc1af1c7372e2938faa9a787026a362fe2R21

```
final String[] suffixes = this.config.get("sonar.ps.file.suffixes").map(s -> s.split(",")).orElse(DEFAULT_FILE_SUFFIXES);

return suffixes;
```

File: sonar-ps-plugin/pom.xml [hunk 7]
```diff
@@ -7,15 +7,16 @@
 	<groupId>org.sonar.plugins</groupId>
 	<artifactId>sonar-ps-plugin</artifactId>
 	<packaging>sonar-plugin</packaging>
-	<version>0.5.4</version>
+	<version>0.7.0</version>
```
Comment (santhonisz) [inline sonar-ps-plugin/pom.xml]: We control the versioning, so just a single minor version bump is required 

```suggestion
	<version>0.6.0</version>
```

File: README.md [hunk 8]
```diff
@@ -49,6 +49,7 @@ Currently there is a possibility to override the following options either on ser
 
 ## Requirements ##
 Different plugin versions supports the following:
+- 0.7.0 - Sonarqube version LTA 2026.2+ and PSScriptAnalyzer version 1.25+ rules, Java 21+
```
Comment (santhonisz) [inline README.md]: Lets add the previous version's release notes too 😄 

Also, I see that you mention the PSScriptAnalyzer 1.25+ and yet there are no rules added? 

Did you run the [regenerateRulesDefinition.ps1](https://github.com/iress/sonar-ps-plugin/blob/master/regenerateRulesDefinition.ps1) script - that will automatically update the required files which you can then commit.

```suggestion
- 0.6.0 - Sonarqube version LTA 2026.1+ and PSScriptAnalyzer version 1.25+ rules, Java 21+
- 0.5.4 - Sonarqube version 10.6+ and PSScriptAnalyzer version 1.22+ rules, Java 17+
```

**Review by santhonisz — CHANGES_REQUESTED** [review]

File: README.md (hunk 8 above)
Comment (hbcartojano) [reply README.md]: Thanks Sam! I've included it in the next commit along with some other improvements.

File: sonar-ps-plugin/src/main/java/org/sonar/plugins/powershell/sensors/TokenizerSensor.java [hunk 9]
```diff
@@ -66,7 +63,7 @@ protected void innerExecute(final SensorContext context) {
         final String scriptFile = parserFile.getAbsolutePath();
         final org.sonar.api.batch.fs.FileSystem fs = context.fileSystem();
         final FilePredicates p = fs.predicates();
-        ExecutorService service = Executors.newWorkStealingPool();
+        ExecutorService service = Executors.newVirtualThreadPerTaskExecutor();
```
Comment (hbcartojano) [inline sonar-ps-plugin/src/main/java/org/sonar/plugins/powershell/sensors/TokenizerSensor.java:66]: I've spent way too much time on this 😬:

When running `mvn clean package`, I'm intermittently getting a failure where CPD tokens are null / not returned. It looks like a timing issue with the `ExecutorService` (`ForkJoinPool` via `newWorkStealingPool`), where downstream processing can observe incomplete results under certain scheduling conditions.

Switching to virtual threads (Java 21) fixed it. I can't point to one exact JDK change, but the `ForkJoinPool` had significant rewrites to support virtual threads in Java 21, and this model fits the workload better anyway: the Java side is mostly I/O orchestration while the heavy lifting happens in the spawned `pwsh` process.

A side effect is standardizing how to test and compile the package through Docker containers which is great to keep in this repo as well.

File: README.md [hunk 10]
```diff
@@ -48,10 +44,31 @@ Currently there is a possibility to override the following options either on ser
...
-- 0.5.1 - Sonarqube version 8.9.2+ and PSScriptAnalyzer version 1.20+ rules, Java 11+
-- 0.5.0 - Sonarqube version 6.7.7+ and PSScriptAnalyzer version 1.18.1 rules, Java 8
-- 0.3.0 - Sonarqube version 6.3+ and PSScriptAnalyzer version 1.17.1 rules, Java 8
-- 0.2.2 - Sonarqube 5.6+ version and PSScriptAnalyzer version 1.17.1 rules, Java 8
+Different plugin versions support the following:
+
+| Plugin Version | SonarQube Version | PSScriptAnalyzer Rules | Java | Notes |
+|---|---|---|---|---|
+| 0.6.0 | LTA 2026.1+ | 1.25+ | 21+ | Current |
+| 0.5.4 | 8.9.2+ | 1.20+ | 17+ | Optimizations and fixes for SonarQube 10+ |
```
Comment (santhonisz) [inline README.md]: Sorry, you missed this from my original review commen

```suggestion
| 0.5.4 | 8.9.2+ | 1.22+ | 17+ | Optimizations and fixes for SonarQube 10+ |
```

File: README.md [hunk 11]
```diff
@@ -48,10 +44,31 @@ Currently there is a possibility to override the following options either on ser
...
+| 0.5.1 | 8.9.2+ | 1.20+ | 11+ |  |
+| 0.5.0 | 6.7.7+ | 1.18.1 | 8 |  |
+| 0.3.0 | 6.3+ | 1.17.1 | 8 |  |
+| 0.2.2 | 5.6+ | 1.17.1 | 8 |  |
+
+## Development ##
+Build and test using Docker Compose:
+- Run tests: `docker compose run --rm test`
+- Build package: `docker compose run --rm build`
+- Use a custom Docker registry: `DEFAULT_DOCKER_REPO=your.registry.com/path docker compose run --rm test`
```
Comment (santhonisz) [inline README.md]: Let's not try to pre-empt what others are doing; this is a public repo and others can figure out what they need to do

```suggestion
```

File: README.md [hunk 12]
```diff
@@ -48,10 +44,31 @@ Currently there is a possibility to override the following options either on ser
...
+
+**Upgrading Java:** Update at least the base image tag in [docker-compose.yml](docker-compose.yml) and `jdk.min.version` in `pom.xml`.
+
+**Upgrading PSScriptAnalyzer:** Run `regenerateRulesDefinition.ps1` to generate new rules, then update `PSSCRIPTANALYZER_VERSION` in the [Dockerfile](Dockerfile).
+
+**Upgrading SonarQube API:** `sonar.apiVersion` is generally backwards compatible. Upgrade `sonar.apiVersion` when you need new API endpoints or when existing ones are deprecated/removed. Also upgrade `sonar.testingHarnessVersion` to match the same SonarQube release.
+
+**Releasing:** Increment version in `pom.xml`, build with `docker compose run --rm build`, create a [GitHub release](https://github.com/gretard/sonar-ps-plugin/releases), and attach the `.jar` from `sonar-ps-plugin/target/`.
```
Comment (santhonisz) [inline README.md]: This doesn't make any sense; why would we create are release on the upstream repo...?

File: sonar-ps-plugin/src/main/java/org/sonar/plugins/powershell/sensors/TokenizerSensor.java (hunk 9 above)
Comment (santhonisz) [reply sonar-ps-plugin/src/main/java/org/sonar/plugins/powershell/sensors/TokenizerSensor.java:66]: Well done on what is hopefully the way forward 👏🏼

File: README.md (hunk 11 above)
Comment (hbcartojano) [reply README.md]: This is mostly just so the next person at Iress knows what to do when they need to use our Docker private registry and update the plugin. It’s just being explicit, but I’m fine to remove it if needed.

File: README.md (hunk 12 above)
Comment (hbcartojano) [reply README.md]: Yes, this should link to our own fork. 😀

**Review by santhonisz — APPROVED** [review]
